//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercedesBenzWebApi.Models.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductID { get; set; }
        public string Model { get; set; }
        public string Name { get; set; }
        public string Slogan { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> Discountable { get; set; }
        public string ImgSrc { get; set; }
    }
}
